import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/general/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} font-sans antialiased relative min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AnimatedGridPattern
            numSquares={30}
            maxOpacity={0.1}
            duration={3}
            repeatDelay={1}
            className="[mask-image:radial-gradient(900px_circle_at_center,white,transparent)] dark:fill-white/[0.03] dark:stroke-white/[0.03] fill-black/[0.03] stroke-black/[0.03]"
          />
          <div className="relative">
            {children}
            <Toaster closeButton richColors />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
